### ISSUE TITLE
Long lines, typed fast. 

### ISSUE THREAD

**Issue by teesloane** [teesloane/husk#8]
Recreate:
- type gibberish quickly.

![screenshot 2016-11-09 23 15 27](https://cloud.githubusercontent.com/assets/12987958/20164383/8438beaa-a6d2-11e6-8084-63352d91ca42.png)

typing normally the text will break into a new line.

the problem seems to to be a long string without any `space` breaks, so the content doesn't know when to break.

**Comment by broneks** [comment]
in css use: `word-break: break-all;`

**Comment by teesloane** [comment]
oooh. will look into this. thanks mate!
